# Here we have some default and internal values, changing some of them may lead to plugin not working properly
txt2img:
  prompts: "dog"
  negative_prompt: ""
  sampler_name: k_euler_a
  steps: 20
  cfg_scale: 12.0
  n_iter: 1
  seed: -1
  base_size: 512
  max_size: 704
  batch_size: 1
  tiling: false

  use_gfpgan: false
  face_restorer: "CodeFormer"
  codeformer_weight: 0.5
  use_realesrgan: false
  realesrgan_model_name: RealESRGAN_x4plus_anime_6B
  sample_path: 'outputs/krita-out'

img2img:
  mode: 0 # 0 - default, 1 - inpaint, 3 - upscale, 2 - loopback (unsupported)

  prompts: "dog"
  negative_prompt: ""
  sampler_name: k_euler_a
  steps: 50
  cfg_scale: 12.0
  denoising_strength: 0.35
  n_iter: 1
  seed: -1
  base_size: 512
  max_size: 704
  batch_size: 1
  tiling: false
  mask_invert: false

  upscale_overlap: 64
  upscaler_name: "None" # None, Lanczos, RealESRGAN

  inpainting_fill: 0
  inpaint_full_res: false
  mask_blur: 0

  use_gfpgan: false
  face_restorer: "CodeFormer"
  codeformer_weight: 0.5
  use_realesrgan: false
  realesrgan_model_name: RealESRGAN_x4plus_anime_6B
  resize_mode: 1
  sample_path: 'outputs/krita-out'

upscale:
  upscaler_name: None
  sample_path: 'outputs/krita-out'
  downscale_first: false

plugin:
  sample_path: 'outputs/krita-in'
